/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c FileServiceDBusAdaptor -a fileservicedbusadaptor.h:fileservicedbusadaptor.cpp pl.mprzybylak.server
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "fileservicedbusadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class FileServiceDBusAdaptor
 */

FileServiceDBusAdaptor::FileServiceDBusAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

FileServiceDBusAdaptor::~FileServiceDBusAdaptor()
{
    // destructor
}

QString FileServiceDBusAdaptor::getRootDirectory()
{
    // handle method call local.FileServiceDBusImpl.getRootDirectory
    QString out0;
    QMetaObject::invokeMethod(parent(), "getRootDirectory", Q_RETURN_ARG(QString, out0));
    return out0;
}

