/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c FileServiceDBusAdaptor -a fileservicedbusadaptor.h:fileservicedbusadaptor.cpp pl.mprzybylak.server -i ../../application/impl/test.h
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef FILESERVICEDBUSADAPTOR_H_1421657601
#define FILESERVICEDBUSADAPTOR_H_1421657601

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "../../application/impl/test.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface local.FileServiceDBusImpl
 */
class FileServiceDBusAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "local.FileServiceDBusImpl")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"local.FileServiceDBusImpl\">\n"
"    <method name=\"getRootDirectory\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"getTest\">\n"
"      <arg direction=\"out\" type=\"(ii)\" name=\"test\"/>\n"
"      <annotation value=\"Test\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    FileServiceDBusAdaptor(QObject *parent);
    virtual ~FileServiceDBusAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString getRootDirectory();
    Test getTest();
Q_SIGNALS: // SIGNALS
};

#endif
