/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -v -c ValueProviderProxy -p valueproviderproxy.h:valueproviderproxy.cpp pl.mprzybylak.Server
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef VALUEPROVIDERPROXY_H_1421221107
#define VALUEPROVIDERPROXY_H_1421221107

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface local.ValueProvider
 */
class ValueProviderProxy: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "local.ValueProvider"; }

public:
    ValueProviderProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ValueProviderProxy();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<int> getValue()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getValue"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace local {
  typedef ::ValueProviderProxy ValueProvider;
}
#endif
