/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c ValueProviderAdapter -a valueprovideradapter.h:valueprovideradapter.cpp pl.mprzybylak.Server
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "valueprovideradapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ValueProviderAdapter
 */

ValueProviderAdapter::ValueProviderAdapter(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ValueProviderAdapter::~ValueProviderAdapter()
{
    // destructor
}

int ValueProviderAdapter::getValue()
{
    // handle method call local.ValueProvider.getValue
    int out0;
    QMetaObject::invokeMethod(parent(), "getValue", Q_RETURN_ARG(int, out0));
    return out0;
}

