/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c ValueProviderAdapter -a valueprovideradapter.h:valueprovideradapter.cpp pl.mprzybylak.Server
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef VALUEPROVIDERADAPTER_H_1421221101
#define VALUEPROVIDERADAPTER_H_1421221101

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface local.ValueProvider
 */
class ValueProviderAdapter: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "local.ValueProvider")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"local.ValueProvider\">\n"
"    <method name=\"getValue\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ValueProviderAdapter(QObject *parent);
    virtual ~ValueProviderAdapter();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int getValue();
Q_SIGNALS: // SIGNALS
};

#endif
